change_prot_dict_6tf = {
    "PD-L1": "CD274",
    "HVEM": "TNFRSF14",
    "Nectin-2": "NECTIN2",
    "CD154": None,
    "CD3": None,
    "CD8": None,
    "NCAM": "NCAM1",
    "CD11c": "ITGAX",
    "HLA-A_B_C": "HLA-A",
    "CD45RA": None,
    "CD123": None,
    "CD49f": "ITGA6",
    "CCR4": None,
    "CD16": "FCGR3A",
    "CD25": None,
    "CD45RO": None,
    "PD-1": None,
    "TIGIT": None,
    "CD20": None,
    "NKp46": "NCR1",
    "CD31": "PECAM1",
    "Podoplanin": "PDPN",
    "CD146": None,
    "CD5": None,
    "CD32": "FCGR2A",
    "CXCR5": None,
    "Integrin-AE": "ITGAE",
    "CD69": None,
    "CD62L": "SELL",
    "CD161": None,
    "CTLA-4": "CTLA4",
    "LAG-3": "LAG3",
    "CD27": None,
    "LAMP-1": "LAMP1",
    "Fas": "FAS",
    "OX40": "TNFRSF4",
    "HLA-DR": "HLA-DRA",
    "CD11b": "ITGAM",
    "CD64": "FCGR1A",
    "Thrombomodulin": "THBD",
    "NKG2D": None,
    "CD35": None,
    "CD57": None,
    "ICOS": None,
    "B7-H2": "ICOSLG",
    "LFA-3": "CD58",
    "CD39": "ENTPD1",
    "CD21": None,
    "CD11a": "ITGAL",
    "CD79b": None,
    "Siglec-1": "SIGLEC1",
    "Integrin-B7": "ITGB7",
    "BAFF-R": "TNFRSF13C",
    "CD42b": "GP1BA",
    "CD54": "ICAM1",
    "P-Selectin": None,
    "TCR-A_B": None,
    "IL-2RB": None,
    "CD267": None,
    "CD41": "ITGA2B",
    "CD137": "TNFRSF9",
    "CD43": "SPN",
    "CD13": "ANPEP",
    "CD2": None,
    "CD29": "ITGB1",
    "CD303": None,
    "CD49b": "ITGA2",
    "CD61": "ITGB3",
    "CD18": "ITGB2",
    "CD38": None,
    "IL-7RA": "IL7R",
    "CD45": "PTPRC",
    "CD22": None,
    "CD71": "TFRC",
    "CD26": "DPP4",
    "CSF-1R": "CSF1R",
    "Neuropilin-1": "NPR1",
    "SIRP-A": "SIRPA",
    "KIR2DL1": None,
    "CD200": None,
    "CD49a": "ITGA1",
    "CD49d": "ITGA4",
    "CD73": None,
    "TREM-1": "TREM1",
    "LOX-1": "OLR1",
    "KIR3DL1": None,
    "CD142": "F3",
    "CRACC": "SLAMF7",
    "CD99": None,
    "PETA-3": "CD151",
    "NTB-A": None,
    "CLEC1B": None,
    "CD94": None,
    "SLAM": None,
    "CD162": "SELPLG",
    "CD85j": "LILRB1",
    "CD23": None,
    "Siglec-7": "SIGLEC7",
    "GPR56": "ADGRG1",
    "NKp80": None,
    "CD131": "CSF2RB",
    "CD116": None,
    "HLA-DR_DP_DQ": "HLA-DRB1",
    "C5aR": "C5AR1",
    "CD49e": "ITGA5",
    "CD51": "ITGAV",
    "ACE": None,
    "P-Selectin": "SELP",
    "CD1c": "CD1C",
}

change_prot_dict_imgl = {
    "PD-L1": "CD274",
    "HVEM": "TNFRSF14",
    "Nectin-2": "NECTIN2",
    "CD154": None,
    "CD3": None,
    "CD8": None,
    "NCAM": "NCAM1",
    "CD11c": "ITGAX",
    "HLA-A_B_C": "HLA-A",
    "CD45RA": None,
    "CD123": None,
    "CD49f": "ITGA6",
    "CCR4": None,
    "CD16": "FCGR3A",
    "CD25": None,
    "CD45RO": None,
    "PD-1": None,
    "TIGIT": None,
    "CD20": None,
    "NKp46": "NCR1",
    "CD31": "PECAM1",
    "Podoplanin": "PDPN",
    "CD146": None,
    "CD5": None,
    "CD32": "FCGR2A",
    "CXCR5": None,
    "Integrin-AE": "ITGAE",
    "CD69": None,
    "CD62L": "SELL",
    "CD161": None,
    "CTLA-4": "CTLA4",
    "LAG-3": "LAG3",
    "CD27": None,
    "LAMP-1": "LAMP1",
    "Fas": "FAS",
    "OX40": "TNFRSF4",
    "HLA-DR": "HLA-DRA",
    "CD11b": "ITGAM",
    "CD64": "FCGR1A",
    "Thrombomodulin": "THBD",
    "NKG2D": None,
    "CD35": None,
    "CD57": None,
    "ICOS": None,
    "B7-H2": "ICOSLG",
    "LFA-3": "CD58",
    "CD39": "ENTPD1",
    "CD21": None,
    "CD11a": "ITGAL",
    "CD79b": None,
    "Siglec-1": "SIGLEC1",
    "Integrin-B7": "ITGB7",
    "BAFF-R": "TNFRSF13C",
    "CD42b": "GP1BA",
    "CD54": "ICAM1",
    "P-Selectin": None,
    "TCR-A_B": None,
    "IL-2RB": None,
    "CD267": None,
    "CD41": "ITGA2B",
    "CD137": "TNFRSF9",
    "CD43": "SPN",
    "CD13": "ANPEP",
    "CD2": None,
    "CD29": "ITGB1",
    "CD303": None,
    "CD49b": None,
    "CD61": "ITGB3",
    "CD18": "ITGB2",
    "CD38": None,
    "IL-7RA": "IL7R",
    "CD45": "PTPRC",
    "CD22": None,
    "CD71": "TFRC",
    "CD26": "DPP4",
    "CSF-1R": "CSF1R",
    "Neuropilin-1": "NPR1",
    "SIRP-A": "SIRPA",
    "KIR2DL1": None,
    "CD200": None,
    "CD49a": None,
    "CD49d": "ITGA4",
    "CD73": None,
    "TREM-1": "TREM1",
    "LOX-1": "OLR1",
    "KIR3DL1": None,
    "CD142": "F3",
    "CRACC": "SLAMF7",
    "CD99": None,
    "PETA-3": "CD151",
    "NTB-A": None,
    "CLEC1B": None,
    "CD94": None,
    "SLAM": None,
    "CD162": "SELPLG",
    "CD85j": None,
    "CD23": None,
    "Siglec-7": "SIGLEC7",
    "GPR56": "ADGRG1",
    "NKp80": None,
    "CD131": "CSF2RB",
    "CD116": None,
    "HLA-DR_DP_DQ": "HLA-DRB1",
    "C5aR": "C5AR1",
    "CD49e": "ITGA5",
    "CD51": "ITGAV",
    "ACE": None,
    "P-Selectin": "SELP",
    "CD1c": "CD1C",
}


def get_protein_marker_labels():
    mic_markers = ["CD45", "CD11b"]

    t_and_b_markers = [
        # T cell markers
        "CD8",
        "CD4",
        "CD3",
        # B cell markers
        "CD19",
        "CD20",
        # TCR
        "TCR-A_B",
        "TCR-V-A7.2",
        "TCR-V-D2",
    ]

    isotype_controls = [
        "Control_hamster_IgG",
        "Control_mouse_IgG1K",
        "Control_mouse_IgG2aK",
        "Control_mouse_IgG2bK",
        "Control_rat_IgG1K",
        "Control_rat_IgG1L",
        "Control_rat_IgG2aK",
        "Control_rat_IgG2bK",
        "Control_rat_IgG2cK",
    ]

    igs = ["IgD", "IgE", "IgK", "IgL", "IgM"]

    mic17 = [
        "CD49e",
        "ADAM10",
        "CD51",
        "PTPRJ",
        "HLA-C",
        "ITGB5",
        "BST2",
        "TREM2",
        "CLU",
        "NRCAM",
        "PSEN1",
        "ACE",
        "PSEN2",
        "SORT1",
        "P2RY12",
        "OPRL1",
        "PLXNB2",
    ]

    target_antibodies = mic_markers + t_and_b_markers + isotype_controls + igs + mic17

    marker_dict = {
        "mic_markers": mic_markers,
        "t_and_b_markers": t_and_b_markers,
        "isotype_controls": isotype_controls,
        "igs": igs,
        "mic17": mic17,
        "targeted_antibodies": target_antibodies,
    }
    return marker_dict


def get_protein_renamed_dict(name):
    return change_prot_dict_6tf if name == "6tf" else change_prot_dict_imgl
